# Generated by Django 5.1.15 on 2026-08-03 20:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0002_strategy_deleted_at_alter_strategy_is_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=8)),
                ('criteria', models.JSONField()),
                ('desc_sha256', models.CharField(max_length=64)),
                ('results', models.JSONField(default=list)),
                ('counts', models.JSONField(default=dict)),
                ('degraded', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, default='', max_length=48)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_runs', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'screener_run',
                'indexes': [models.Index(fields=['user', 'strategy', '-created_at'], name='screener_ru_user_id_3a0788_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING'])), fields=('user', 'strategy'), name='uniq_active_screen_run_per_user_strategy')],
            },
        ),
    ]
