# Generated by Django 5.1.15 on 2026-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVectorSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(db_index=True, default='MARKET', max_length=16)),
                ('ts', models.DateTimeField(db_index=True)),
                ('features', models.JSONField(default=dict)),
                ('raw_features', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'regime_feature_snapshot',
                'indexes': [models.Index(fields=['scope', '-ts'], name='regime_feat_scope_630f94_idx')],
                'unique_together': {('scope', 'ts')},
            },
        ),
        migrations.CreateModel(
            name='HMMModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=48, unique=True)),
                ('n_states', models.PositiveSmallIntegerField(default=4)),
                ('params', models.JSONField(default=dict)),
                ('state_labels', models.JSONField(default=dict)),
                ('train_ll', models.FloatField(blank=True, null=True)),
                ('holdout_ll', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('trained_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'regime_hmm_model',
                'indexes': [models.Index(fields=['active', '-trained_at'], name='regime_hmm__active_c0287c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegimeObservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('MARKET', 'Market')], db_index=True, default='MARKET', max_length=16)),
                ('ts', models.DateTimeField(db_index=True)),
                ('label', models.CharField(max_length=16)),
                ('rule_bucket', models.CharField(max_length=16)),
                ('rule_score', models.FloatField(default=0.0)),
                ('hmm_state', models.CharField(blank=True, default='', max_length=16)),
                ('hmm_probs', models.JSONField(default=dict)),
                ('top_features', models.JSONField(default=list)),
                ('model_version', models.CharField(blank=True, default='', max_length=48)),
                ('model_degraded', models.BooleanField(default=False)),
                ('ensemble_version', models.CharField(default='v1', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'regime_observation',
                'indexes': [models.Index(fields=['scope', '-ts'], name='regime_obse_scope_3bea70_idx')],
                'unique_together': {('scope', 'ts')},
            },
        ),
    ]
