# Generated by Django 5.0.14 on 2026-05-01 21:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(db_index=True, max_length=128)),
                ('salt', models.CharField(max_length=32)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_backup_code',
            },
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_encrypted', models.BinaryField()),
                ('verified', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_mfa_device',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('language', models.CharField(default='en', max_length=8)),
                ('notification_email', models.BooleanField(default=True)),
                ('default_broker_id', models.UUIDField(blank=True, null=True)),
                ('terms_version_accepted', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_user_profile',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='authevent',
            new_name='users_auth__user_id_4e31f1_idx',
            old_name='users_authe_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='failedloginattempt',
            new_name='users_faile_email_a62e66_idx',
            old_name='users_faile_email_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtokenfamily',
            new_name='users_refre_user_id_965cc9_idx',
            old_name='users_refre_user_id_idx',
        ),
        migrations.AddField(
            model_name='refreshtokenfamily',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshtokenfamily',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshtokenfamily',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='authevent',
            name='event_type',
            field=models.CharField(choices=[('register', 'Register'), ('verify_email', 'Verify Email'), ('login_ok', 'Login Ok'), ('login_fail', 'Login Fail'), ('logout', 'Logout'), ('refresh_ok', 'Refresh Ok'), ('refresh_reuse', 'Refresh Reuse'), ('family_revoked', 'Family Revoked'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('account_locked', 'Account Locked'), ('resend_verification', 'Resend Verification'), ('mfa_enrolled', 'Mfa Enrolled'), ('mfa_disabled', 'Mfa Disabled'), ('mfa_challenge_ok', 'Mfa Challenge Ok'), ('mfa_challenge_fail', 'Mfa Challenge Fail'), ('backup_code_used', 'Backup Code Used'), ('backup_codes_regenerated', 'Backup Codes Regenerated'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated'), ('session_revoked', 'Session Revoked')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='backupcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='backupcode',
            index=models.Index(fields=['user', 'used_at'], name='users_backu_user_id_ac9866_idx'),
        ),
    ]
