# Generated by Django 5.0.14 on 2026-05-02 10:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mfa_and_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='event_type',
            field=models.CharField(choices=[('register', 'Register'), ('verify_email', 'Verify Email'), ('login_ok', 'Login Ok'), ('login_fail', 'Login Fail'), ('logout', 'Logout'), ('refresh_ok', 'Refresh Ok'), ('refresh_reuse', 'Refresh Reuse'), ('family_revoked', 'Family Revoked'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('account_locked', 'Account Locked'), ('resend_verification', 'Resend Verification'), ('mfa_enrolled', 'Mfa Enrolled'), ('mfa_disabled', 'Mfa Disabled'), ('mfa_challenge_ok', 'Mfa Challenge Ok'), ('mfa_challenge_fail', 'Mfa Challenge Fail'), ('backup_code_used', 'Backup Code Used'), ('backup_codes_regenerated', 'Backup Codes Regenerated'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated'), ('session_revoked', 'Session Revoked'), ('oauth_login_ok', 'Oauth Login Ok'), ('oauth_user_created', 'Oauth User Created'), ('oauth_linked', 'Oauth Linked'), ('oauth_exchange_ok', 'Oauth Exchange Ok'), ('oauth_exchange_fail', 'Oauth Exchange Fail')], max_length=32),
        ),
        migrations.CreateModel(
            name='OAuthExchangeCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='google', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_exchange_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_oauth_exchange_code',
                'indexes': [models.Index(fields=['user', 'consumed_at'], name='users_oauth_user_id_596da7_idx')],
            },
        ),
    ]
