# Generated by Django 5.1.15 on 2026-07-12 13:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_drop_auth_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='TermsDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy')], db_index=True, max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=256)),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_terms_document',
                'indexes': [models.Index(fields=['kind', 'effective_from'], name='users_terms_kind_5e72e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='uq_terms_kind_version')],
            },
        ),
        migrations.CreateModel(
            name='DataExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('file_key', models.CharField(blank=True, default='', max_length=256)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_data_export_job',
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_data__user_id_f7b989_idx')],
            },
        ),
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tos_version', models.CharField(max_length=32)),
                ('privacy_version', models.CharField(max_length=32)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_terms_acceptance',
                'indexes': [models.Index(fields=['user', 'accepted_at'], name='users_terms_user_id_0dd447_idx')],
            },
        ),
    ]
