# Generated by Django 5.1.15 on 2026-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_flow_and_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtokenfamily',
            name='previous_jti',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
