# Generated by Django 5.1.15 on 2026-07-09 20:12

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_feature_flag',
            },
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua', models.CharField(blank=True, default='', max_length=512)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_started', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonated_as', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_impersonation_session',
                'indexes': [models.Index(fields=['actor', '-started_at'], name='admin_imper_actor_i_b0d750_idx'), models.Index(fields=['target', '-started_at'], name='admin_imper_target__bddd6a_idx')],
            },
        ),
    ]
