# Generated by Django 5.1.15 on 2026-07-29 17:28
"""#46 — split soft-delete (``deleted_at``) from the arm/disarm toggle
(``is_enabled``).

Data rule: under the old single-flag semantics the only user-facing paths that
set ``is_enabled=False`` were Delete and the list toggle, and the list hid both
identically — so every pre-existing disabled row is stamped as a legacy
soft-delete. Rows that were meant to be *paused but kept* must be re-enabled
BEFORE this migration deploys (done for the one known case on prod,
sepa_vcp_strategy_v2). Reverse drops the column and keeps ``is_enabled``.
"""

from django.db import migrations, models
from django.utils import timezone


def _mark_legacy_soft_deletes(apps, schema_editor):
    Strategy = apps.get_model("strategies", "Strategy")
    Strategy.objects.filter(is_enabled=False, deleted_at__isnull=True).update(
        deleted_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft-delete timestamp. NULL = live. Set by user DELETE; row is hidden from all lists and rejects alerts (#46).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Live-execution toggle (arm/disarm). False = paused: still listed, but webhook alerts are rejected. Deletion is ``deleted_at``, not this flag (#46).",
            ),
        ),
        migrations.RunPython(_mark_legacy_soft_deletes, migrations.RunPython.noop),
    ]
