# Generated by Django 5.1.15 on 2026-07-07 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliasTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=128, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=16)),
            ],
            options={
                'db_table': 'sentiment_alias_table',
            },
        ),
        migrations.CreateModel(
            name='TickerRegistry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('is_etf', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sentiment_ticker_registry',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('FMP', 'FMP'), ('EDGAR', 'SEC EDGAR'), ('BENZINGA', 'Benzinga'), ('NASDAQ_HALTS', 'Nasdaq halts'), ('FINNHUB', 'Finnhub'), ('ALPACA', 'Alpaca News')], db_index=True, max_length=16)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True, default='')),
                ('dedup_hash', models.CharField(max_length=64, unique=True)),
                ('symbols', models.JSONField(default=list)),
                ('symbols_text', models.CharField(blank=True, db_index=True, default='', max_length=256)),
                ('material', models.BooleanField(db_index=True, default=False)),
                ('tier1_scored', models.BooleanField(db_index=True, default=False)),
                ('tier2_scored', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sentiment_news_article',
                'indexes': [models.Index(fields=['source', '-published_at'], name='sentiment_n_source_cfa6a0_idx'), models.Index(fields=['tier1_scored', 'material'], name='sentiment_n_tier1_s_8b94f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMInferenceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prompt_version', models.CharField(default='', max_length=16)),
                ('valid', models.BooleanField(default=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_logs', to='sentiment.newsarticle')),
            ],
            options={
                'db_table': 'sentiment_llm_inference_log',
            },
        ),
        migrations.CreateModel(
            name='SentimentScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(db_index=True, max_length=32)),
                ('polarity', models.FloatField(default=0.0)),
                ('impact', models.FloatField(default=0.0)),
                ('window_minutes', models.IntegerField(default=1440)),
                ('components', models.JSONField(default=dict)),
                ('produced_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sentiment_score',
                'indexes': [models.Index(fields=['scope', '-produced_at'], name='sentiment_s_scope_4515b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(choices=[('FINBERT', 'FinBERT'), ('LLAMA', 'Llama'), ('FALLBACK', 'Fallback')], max_length=12)),
                ('positive', models.FloatField(default=0.0)),
                ('negative', models.FloatField(default=0.0)),
                ('neutral', models.FloatField(default=0.0)),
                ('polarity', models.FloatField(default=0.0)),
                ('label', models.CharField(blank=True, default='', max_length=12)),
                ('confidence', models.FloatField(default=0.0)),
                ('impact', models.IntegerField(blank=True, null=True)),
                ('horizon_days', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='sentiment.newsarticle')),
            ],
            options={
                'db_table': 'sentiment_article_score',
                'unique_together': {('article', 'model')},
            },
        ),
    ]
