# Generated by Django 5.1.15 on 2026-07-07 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_asset_class_order_future_expiry_and_more'),
        ('strategies', '0001_initial'),
        ('webhooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=3, default=1.0, max_digits=6)),
                ('max_position_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('max_concurrent', models.PositiveIntegerField(default=5)),
                ('daily_loss_usd', models.DecimalField(decimal_places=2, default=1000.0, max_digits=14)),
                ('daily_loss_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('leverage_cap', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('permitted_asset_classes', models.JSONField(default=list)),
                ('soft_stop_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('hard_stop_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('strict_mode', models.BooleanField(default=False)),
                ('atr_factor', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_profile',
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DAILY_LOSS_BREACH', 'Daily loss breach'), ('KILL_SWITCH_ON', 'Kill switch on'), ('KILL_SWITCH_OFF', 'Kill switch off'), ('SOFT_STOP', 'Soft stop'), ('SIZING_REJECT', 'Sizing reject'), ('FLATTEN', 'Flatten')], db_index=True, max_length=24)),
                ('scope', models.CharField(blank=True, default='', max_length=16)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_event',
                'indexes': [models.Index(fields=['user', '-created_at'], name='risk_event_user_id_d83b8d_idx'), models.Index(fields=['type', '-created_at'], name='risk_event_type_357af4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SizingDecision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, default='', max_length=32)),
                ('requested_qty', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('computed_qty', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('result', models.CharField(choices=[('OK', 'Sized'), ('REJECT', 'Rejected')], default='OK', max_length=8)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=48)),
                ('inputs', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizing_decisions', to='webhooks.alertmessage')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizing_decisions', to='orders.order')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizing_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_sizing_decision',
                'indexes': [models.Index(fields=['user', '-created_at'], name='risk_sizing_user_id_97945f_idx'), models.Index(fields=['order'], name='risk_sizing_order_i_a40be2_idx')],
            },
        ),
    ]
