# Generated by Django 5.1.15 on 2026-07-07 18:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('ts', models.DateTimeField()),
                ('broker_exec_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders_fill',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=24)),
                ('qty', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('market_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders_position',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_order_id', models.CharField(max_length=128, unique=True)),
                ('broker_order_id', models.CharField(blank=True, default='', max_length=128)),
                ('symbol', models.CharField(max_length=24)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('order_type', models.CharField(choices=[('MKT', 'Market'), ('LMT', 'Limit')], default='MKT', max_length=8)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('time_in_force', models.CharField(choices=[('DAY', 'Day')], default='DAY', max_length=8)),
                ('status', models.CharField(choices=[('PENDING_SUBMIT', 'Pending submit'), ('SUBMITTED', 'Submitted'), ('PARTIAL', 'Partially filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING_SUBMIT', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('filled_qty', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='brokers.brokeraccount')),
            ],
            options={
                'db_table': 'orders_order',
            },
        ),
    ]
