# Generated by Django 5.1.15 on 2026-07-07 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_brokeraccount_ts_access_token_enc_and_more'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='asset_class',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF'), ('OPTION', 'Option'), ('FUTURE', 'Future')], default='STOCK', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='future_expiry',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='future_root',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='option_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='option_right',
            field=models.CharField(blank=True, choices=[('CALL', 'Call'), ('PUT', 'Put')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='option_strike',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('MKT', 'Market'), ('LMT', 'Limit'), ('STP', 'Stop'), ('STP_LMT', 'Stop limit')], default='MKT', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('BUY_TO_OPEN', 'Buy to open'), ('SELL_TO_OPEN', 'Sell to open'), ('BUY_TO_CLOSE', 'Buy to close'), ('SELL_TO_CLOSE', 'Sell to close')], max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='symbol',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_in_force',
            field=models.CharField(choices=[('DAY', 'Day'), ('GTC', 'Good til cancelled'), ('IOC', 'Immediate or cancel')], default='DAY', max_length=8),
        ),
        migrations.CreateModel(
            name='ReconEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=32)),
                ('asset_class', models.CharField(default='STOCK', max_length=8)),
                ('kind', models.CharField(choices=[('DRIFT', 'Drift detected'), ('HEAL', 'Healed toward broker'), ('RESOLVED', 'Resolved (no longer drifting)')], default='DRIFT', max_length=8)),
                ('our_qty', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('broker_qty', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_events', to='brokers.brokeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_recon_event',
                'indexes': [models.Index(fields=['user', '-created_at'], name='orders_reco_user_id_49aa9d_idx'), models.Index(fields=['broker_account', 'symbol', '-created_at'], name='orders_reco_broker__260cd1_idx')],
            },
        ),
    ]
