# Generated by Django 5.1.15 on 2026-07-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_tradinghalt_auto_tradinghalt_level_and_more'),
        ('orders', '0003_order_asset_class_order_future_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill',
            name='broker_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='brokers.brokeraccount'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='broker_exec_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='fill',
            unique_together={('broker_account', 'broker_exec_id')},
        ),
        migrations.AddIndex(
            model_name='fill',
            index=models.Index(fields=['broker_exec_id'], name='orders_fill_broker__f4ac36_idx'),
        ),
    ]
