# Generated by Django 5.1.15 on 2026-07-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_fill_broker_account_alter_fill_broker_exec_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_SUBMIT', 'Pending submit'), ('SUBMITTED', 'Submitted'), ('PARTIAL', 'Partially filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('NEEDS_RECONCILE', 'Needs reconcile')], default='PENDING_SUBMIT', max_length=16),
        ),
    ]
