# Generated by Django 5.1.15 on 2026-07-09 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditVerifierState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_verified_id', models.BigIntegerField(default=0)),
                ('last_verified_hash', models.CharField(blank=True, default='', max_length=64)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, default='', max_length=16)),
            ],
            options={
                'db_table': 'audit_verifier_state',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('auth.register', 'auth: Register'), ('auth.verify_email', 'auth: Verify Email'), ('auth.login_ok', 'auth: Login Ok'), ('auth.login_fail', 'auth: Login Fail'), ('auth.logout', 'auth: Logout'), ('auth.refresh_ok', 'auth: Refresh Ok'), ('auth.refresh_reuse', 'auth: Refresh Reuse'), ('auth.family_revoked', 'auth: Family Revoked'), ('auth.password_reset_requested', 'auth: Password Reset Requested'), ('auth.password_reset_confirmed', 'auth: Password Reset Confirmed'), ('auth.account_locked', 'auth: Account Locked'), ('auth.resend_verification', 'auth: Resend Verification'), ('auth.mfa_enrolled', 'auth: Mfa Enrolled'), ('auth.mfa_disabled', 'auth: Mfa Disabled'), ('auth.mfa_challenge_ok', 'auth: Mfa Challenge Ok'), ('auth.mfa_challenge_fail', 'auth: Mfa Challenge Fail'), ('auth.backup_code_used', 'auth: Backup Code Used'), ('auth.backup_codes_regenerated', 'auth: Backup Codes Regenerated'), ('auth.password_changed', 'auth: Password Changed'), ('auth.profile_updated', 'auth: Profile Updated'), ('auth.session_revoked', 'auth: Session Revoked'), ('auth.oauth_login_ok', 'auth: Oauth Login Ok'), ('auth.oauth_user_created', 'auth: Oauth User Created'), ('auth.oauth_linked', 'auth: Oauth Linked'), ('auth.oauth_exchange_ok', 'auth: Oauth Exchange Ok'), ('auth.oauth_exchange_fail', 'auth: Oauth Exchange Fail'), ('broker.connect', 'Broker connected'), ('broker.disconnect', 'Broker disconnected'), ('broker.mode_change', 'Broker mode changed'), ('order.submitted', 'Order submitted'), ('order.fill_ingested', 'Fill ingested'), ('strategy.created', 'Strategy created'), ('strategy.updated', 'Strategy updated'), ('strategy.deleted', 'Strategy deleted'), ('strategy.secret_rotated', 'Webhook secret rotated'), ('risk.profile_changed', 'Risk profile changed'), ('risk.halt_engaged', 'Kill switch engaged'), ('risk.halt_released', 'Kill switch released'), ('admin.user_disabled', 'User disabled'), ('admin.user_enabled', 'User enabled'), ('admin.impersonation_started', 'Impersonation started'), ('admin.impersonation_stopped', 'Impersonation stopped'), ('admin.impersonated_read', 'Impersonated read'), ('admin.platform_halt_engaged', 'Platform halt engaged'), ('admin.platform_halt_released', 'Platform halt released'), ('flag.flipped', 'Feature flag flipped'), ('audit.integrity_failure', 'Audit integrity failure'), ('audit.verifier_completed', 'Audit verifier completed')], max_length=64)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('data_before', models.JSONField(blank=True, null=True)),
                ('data_after', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua', models.CharField(blank=True, default='', max_length=512)),
                ('prev_hash', models.CharField(max_length=64)),
                ('self_hash', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='audit_log_user_id_7b3857_idx'), models.Index(fields=['actor', 'occurred_at'], name='audit_log_actor_i_eb9bde_idx'), models.Index(fields=['event_type', 'occurred_at'], name='audit_log_event_t_344378_idx'), models.Index(fields=['entity_type', 'entity_id', 'occurred_at'], name='audit_log_entity__accb63_idx'), models.Index(fields=['occurred_at'], name='audit_log_occurre_02ec46_idx')],
            },
        ),
    ]
