# Generated by Django 5.1.15 on 2026-07-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('auth.register', 'auth: Register'), ('auth.verify_email', 'auth: Verify Email'), ('auth.login_ok', 'auth: Login Ok'), ('auth.login_fail', 'auth: Login Fail'), ('auth.logout', 'auth: Logout'), ('auth.refresh_ok', 'auth: Refresh Ok'), ('auth.refresh_reuse', 'auth: Refresh Reuse'), ('auth.family_revoked', 'auth: Family Revoked'), ('auth.password_reset_requested', 'auth: Password Reset Requested'), ('auth.password_reset_confirmed', 'auth: Password Reset Confirmed'), ('auth.account_locked', 'auth: Account Locked'), ('auth.resend_verification', 'auth: Resend Verification'), ('auth.mfa_enrolled', 'auth: Mfa Enrolled'), ('auth.mfa_disabled', 'auth: Mfa Disabled'), ('auth.mfa_challenge_ok', 'auth: Mfa Challenge Ok'), ('auth.mfa_challenge_fail', 'auth: Mfa Challenge Fail'), ('auth.backup_code_used', 'auth: Backup Code Used'), ('auth.backup_codes_regenerated', 'auth: Backup Codes Regenerated'), ('auth.password_changed', 'auth: Password Changed'), ('auth.profile_updated', 'auth: Profile Updated'), ('auth.session_revoked', 'auth: Session Revoked'), ('auth.oauth_login_ok', 'auth: Oauth Login Ok'), ('auth.oauth_user_created', 'auth: Oauth User Created'), ('auth.oauth_linked', 'auth: Oauth Linked'), ('auth.oauth_exchange_ok', 'auth: Oauth Exchange Ok'), ('auth.oauth_exchange_fail', 'auth: Oauth Exchange Fail'), ('broker.connect', 'Broker connected'), ('broker.disconnect', 'Broker disconnected'), ('broker.mode_change', 'Broker mode changed'), ('order.submitted', 'Order submitted'), ('order.fill_ingested', 'Fill ingested'), ('strategy.created', 'Strategy created'), ('strategy.updated', 'Strategy updated'), ('strategy.deleted', 'Strategy deleted'), ('strategy.secret_rotated', 'Webhook secret rotated'), ('risk.profile_changed', 'Risk profile changed'), ('risk.halt_engaged', 'Kill switch engaged'), ('risk.halt_released', 'Kill switch released'), ('admin.user_disabled', 'User disabled'), ('admin.user_enabled', 'User enabled'), ('admin.impersonation_started', 'Impersonation started'), ('admin.impersonation_stopped', 'Impersonation stopped'), ('admin.impersonated_read', 'Impersonated read'), ('admin.platform_halt_engaged', 'Platform halt engaged'), ('admin.platform_halt_released', 'Platform halt released'), ('flag.flipped', 'Feature flag flipped'), ('audit.integrity_failure', 'Audit integrity failure'), ('audit.verifier_completed', 'Audit verifier completed'), ('security.mfa_stepup_throttled', 'MFA step-up throttled'), ('account.export_requested', 'Data export requested'), ('account.export_ready', 'Data export ready'), ('account.export_failed', 'Data export failed'), ('account.delete_requested', 'Account deletion requested'), ('account.delete_cancelled', 'Account deletion cancelled'), ('account.anonymized', 'Account anonymized'), ('terms.accepted', 'Terms accepted')], max_length=64),
        ),
    ]
