# Generated by Django 5.1.15 on 2026-07-07 18:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_json', models.JSONField(default=dict, help_text='Inbound payload with the `sig` field stripped.')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('INVALID', 'Invalid')], default='RECEIVED', max_length=12)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=48)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_messages', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webhooks_alert_message',
                'indexes': [models.Index(fields=['user', '-received_at'], name='webhooks_al_user_id_1f4967_idx'), models.Index(fields=['idempotency_key'], name='webhooks_al_idempot_2c994e_idx')],
            },
        ),
    ]
