# Generated by Django 5.1.15 on 2026-07-17 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
        ('webhooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alertmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('user', 'idempotency_key'), name='uniq_alert_user_idempotency'),
        ),
    ]
