# Generated by Django 5.1.15 on 2026-07-07 18:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broker', models.CharField(choices=[('ALPACA', 'Alpaca')], default='ALPACA', max_length=16)),
                ('mode', models.CharField(choices=[('PAPER', 'Paper')], default='PAPER', max_length=8)),
                ('api_key_id_enc', models.BinaryField(help_text='Fernet-wrapped Alpaca API key ID.')),
                ('api_secret_enc', models.BinaryField(help_text='Fernet-wrapped Alpaca API secret.')),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('nickname', models.CharField(blank=True, default='', max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONNECTED', 'Connected'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('ERROR', 'Error')], default='PENDING', max_length=12)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brokers_account',
            },
        ),
        migrations.CreateModel(
            name='BrokerCallAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('broker', models.CharField(default='ALPACA', max_length=16)),
                ('endpoint', models.CharField(help_text='SDK method name, e.g. submit_order.', max_length=64)),
                ('method', models.CharField(default='GET', max_length=8)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_audits', to='brokers.brokeraccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brokers_call_audit',
            },
        ),
        migrations.CreateModel(
            name='TradingHalt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(blank=True, help_text='NULL = user-level halt (all strategies).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trading_halts', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_halts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brokers_trading_halt',
            },
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['user', 'is_default'], name='brokers_acc_user_id_e2416e_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeraccount',
            index=models.Index(fields=['broker', 'mode'], name='brokers_acc_broker_766c05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokeraccount',
            unique_together={('user', 'broker', 'account_number')},
        ),
        migrations.AddIndex(
            model_name='brokercallaudit',
            index=models.Index(fields=['broker_account', 'created_at'], name='brokers_cal_broker__505915_idx'),
        ),
        migrations.AddIndex(
            model_name='brokercallaudit',
            index=models.Index(fields=['endpoint', 'ok'], name='brokers_cal_endpoin_18110d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradinghalt',
            index=models.Index(fields=['user', 'released_at'], name='brokers_tra_user_id_be7b73_idx'),
        ),
        migrations.AddIndex(
            model_name='tradinghalt',
            index=models.Index(fields=['strategy', 'released_at'], name='brokers_tra_strateg_3cd1cc_idx'),
        ),
    ]
