# Generated by Django 5.1.15 on 2026-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='ts_access_token_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='ts_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='ts_refresh_token_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='ts_scope',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='brokeraccount',
            name='broker',
            field=models.CharField(choices=[('ALPACA', 'Alpaca'), ('TRADESTATION', 'TradeStation')], default='ALPACA', max_length=16),
        ),
        migrations.AlterField(
            model_name='brokeraccount',
            name='mode',
            field=models.CharField(choices=[('PAPER', 'Paper'), ('LIVE', 'Live')], default='PAPER', max_length=8),
        ),
    ]
