# Generated by Django 5.1.15 on 2026-07-07 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_brokeraccount_ts_access_token_enc_and_more'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinghalt',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradinghalt',
            name='level',
            field=models.CharField(choices=[('L0', 'Strategy'), ('L1', 'User (global)'), ('L2', 'Daily-loss circuit breaker'), ('L3', 'Platform')], db_index=True, default='L1', max_length=2),
        ),
        migrations.AlterField(
            model_name='tradinghalt',
            name='user',
            field=models.ForeignKey(blank=True, help_text='NULL = platform-wide (L3).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trading_halts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tradinghalt',
            index=models.Index(fields=['level', 'released_at'], name='brokers_tra_level_469b28_idx'),
        ),
    ]
