# Generated by Django 5.1.15 on 2026-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('tf', models.CharField(choices=[('1m', '1 minute'), ('5m', '5 minutes'), ('15m', '15 minutes'), ('1h', '1 hour'), ('1d', '1 day')], max_length=4)),
                ('ts', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=18)),
                ('high', models.DecimalField(decimal_places=6, max_digits=18)),
                ('low', models.DecimalField(decimal_places=6, max_digits=18)),
                ('close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('volume', models.BigIntegerField(default=0)),
                ('source', models.CharField(default='FMP', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'marketdata_bar',
                'indexes': [models.Index(fields=['symbol', 'tf', 'ts'], name='marketdata__symbol_7ae756_idx')],
                'unique_together': {('symbol', 'tf', 'ts')},
            },
        ),
        migrations.CreateModel(
            name='MacroSeries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('series_id', models.CharField(db_index=True, max_length=32)),
                ('ts', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(default='FRED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'marketdata_macro_series',
                'indexes': [models.Index(fields=['series_id', 'ts'], name='marketdata__series__b864f6_idx')],
                'unique_together': {('series_id', 'ts')},
            },
        ),
    ]
