# Generated by Django 5.1.15 on 2026-08-01 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataProviderKey",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("FMP", "Financial Modeling Prep"),
                            ("FRED", "FRED (St. Louis Fed)"),
                        ],
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "key_encrypted",
                    models.BinaryField(
                        help_text="Fernet-wrapped API key (platform KEK)."
                    ),
                ),
                (
                    "key_hint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Last 4 chars, display-only; empty for short keys.",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marketdata_provider_key",
            },
        ),
    ]
