# Generated by Django 5.1.15 on 2026-07-08 12:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('CANCELLING', 'Cancelling'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=12)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('loading', 'Loading'), ('sweeping', 'Sweeping'), ('replaying', 'Replaying'), ('reporting', 'Reporting')], default='queued', max_length=12)),
                ('pct', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=48)),
                ('error_message', models.CharField(blank=True, default='', max_length=512)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('metrics_hash', models.CharField(blank=True, default='', max_length=64)),
                ('retention_days', models.PositiveSmallIntegerField(default=90)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backtest_run',
            },
        ),
        migrations.CreateModel(
            name='BacktestReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('json', models.JSONField(blank=True, null=True)),
                ('html', models.BinaryField(blank=True, null=True)),
                ('pdf', models.BinaryField(blank=True, null=True)),
                ('html_bytes', models.IntegerField(default=0)),
                ('pdf_bytes', models.IntegerField(default=0)),
                ('json_bytes', models.IntegerField(default=0)),
                ('evicted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='backtest.backtestrun')),
            ],
            options={
                'db_table': 'backtest_report',
            },
        ),
        migrations.CreateModel(
            name='BacktestSegment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=16)),
                ('window_index', models.PositiveSmallIntegerField()),
                ('train_start', models.DateField()),
                ('train_end', models.DateField()),
                ('test_start', models.DateField()),
                ('test_end', models.DateField()),
                ('best_params', models.JSONField(default=dict)),
                ('oos_metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='backtest.backtestrun')),
            ],
            options={
                'db_table': 'backtest_segment',
            },
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['user', '-created_at'], name='backtest_ru_user_id_07be36_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['status'], name='backtest_ru_status_0d4b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestsegment',
            index=models.Index(fields=['run', 'symbol', 'window_index'], name='backtest_se_run_id_fa2182_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backtestsegment',
            unique_together={('run', 'symbol', 'window_index')},
        ),
    ]
